### ISSUE TITLE
Hard depedency on CmfMenuBundle

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/ContentBundle#126]
So I added the ContentBundle to my composer. And than ran into an error upon cache clearing that
Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface is missing.

I checked the composer and it seems the  "CmfMenuBundle" is in the "require-dev" requirement. Does this mean it has to be moved to the "require" part?

**Comment by lsmith77** [comment]
no .. that would be a bug. can you paste the entire stack trace?

**Comment by lsmith77** [comment]
can you also pastebin your composer.json dependencies?

**Comment by ConneXNL** [comment]
Well the menu bundle is being used in:
symfony-cmf/content-bundle/Model/StaticContent.php

**Comment by dbu** [comment]
the idea was that when the menu is not available, https://github.com/symfony-cmf/ContentBundle/blob/master/Model/StaticContentBase.php is used. i fear that when phpcr-odm is activated, the cache warmer starts to try to create the proxy for https://github.com/symfony-cmf/ContentBundle/blob/master/Doctrine/Phpcr/StaticContent.php and fails on that.

not sure how to properly configure this or if menu bundle is a requirement as soon as phpcr-odm is activated. as the bundle does not do much else than that, maybe we should just depend on the menu bundle. the same will be with RoutingBundle, StaticContent also uses an interface from routing.

**Comment by lsmith77** [comment]
hmm is there no way we can instruct the proxy warmer?
