### ISSUE TITLE
ContentDocument required in ContentController

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/ContentBundle#127]
I was recently trying to render a template with the routing bundle. The contentbundle seems to provide a default controller one can use to render a simple template.

However, https://github.com/symfony-cmf/ContentBundle/blob/master/Controller/ContentController.php#L76 says a content document is a required parameter. In practice this means that I cannot render a simple template without providing a content document.

The routing bundle's sonata admin does not require you to provide a content document for a route.
By changing https://github.com/symfony-cmf/ContentBundle/blob/master/Controller/ContentController.php#L76 to default to "null", I was able to just make the template run without needing a content document.

I am not sure if this intended.

**Comment by lsmith77** [comment]
yeah, the Bundle is mostly about rendering Documents .. but I guess allowing and empty value there doesn't really hurt ..

**Comment by dbu** [comment]
i would prefer to keep it required to detect errors. but provide an optional route enhancer that can set a different controller action when there is no document. next to [default_controller](http://symfony.com/doc/current/cmf/bundles/routing/configuration.html#default-controller), maybe call it no_content_controller (or a better name if you have an idea). 

then we would write a new enhancer in https://github.com/symfony-cmf/Routing/tree/master/Enhancer (i think none of the existing fits, it would rather be a FieldMissingEnhancer or something like that) and configure that enhancer if the no_content_controller is configured in the bundle.

do you want to do a pull request for this @ConneXNL ?

**Comment by dbu** [comment]
ping @ConneXNL

**Comment by WouterJ** [comment]
If there is no content document, and you just want to render a template. Why not use the one in the FrameworkBundle? (http://symfony.com/doc/current/cookbook/templating/render_without_controller.html )

I guess we need to change the admin, so that content is required when using the ContentBundle.

**Comment by dbu** [comment]
it could make sense to be able to just configure a route controllers_by_type that leads to a specific template without content and use the framework bundle controller.

this issue then belongs to the RoutingBundle and not here.
