### ISSUE TITLE
Add `Content-Language` response header according to locale of content

### ISSUE THREAD

**Issue by eggyal** [symfony-cmf/ContentBundle#128]

**Comment by lsmith77** [comment]
i think it would make sense to add a Response listener inside the LocaleBundle for this purpose:
https://github.com/lunetics/LocaleBundle

**Comment by dbu** [comment]
> i think it would make sense to add a Response listener inside the
> LocaleBundle for this purpose:
> https://github.com/lunetics/LocaleBundle

but it would be a phpcr-odm question to know the actual language of the
main content. it could be that i request german but get the fallback
content in english. the content is then actually english, even though
the LocaleBundle would claim its german.

we could do this in the default content handler, by looking at the
actual locale of the main content, seems not that wrong to me.
