### ISSUE TITLE
Issue when editing items from the document tree 

### ISSUE THREAD

**Issue by Yaghiyah** [symfony-cmf/ContentBundle#132]
when I edit *any* node item from the document tree, I keep getting an error. 

Example: When I edit a node from tree in the admin tool  i.e cms/route/test, I am able to get to the edit page when I hit the edit operation is successful, however when I click on the same node I get this error... 
 
An exception has been thrown during the rendering of a template ("Can not determine the prefix. Either this is a new, unpersisted document or the listener that calls setPrefix is not set up correctly.") in SonataAdminBundle:CRUD:base_edit.html.twig at line 34.

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Can not determine the prefix. Either this is a new, unpersisted document or the listener that calls setPrefix is not set up correctly.") in "SonataAdminBundle:CRUD:base_edit.html.twig" at line 34." at D:\website\public_html\app\cache\dev\classes.php line 4685 

Another odd issue is all the labels in sonta admin tool is prefixed see attachment.

![download](https://cloud.githubusercontent.com/assets/1174161/9181684/90e1e742-3fa6-11e5-96f1-4cd71d48d355.png)

**Comment by dbu** [comment]
routes need to be placed under the location you configured on
cmf_routing. if you did not specify anything, that location is
/cms/routes. trying to save a route to any other location results in an
error.

there seems to be an issue with this when editing related routes on a
content that where placed at an invalid location previously - in that
case you need to move the route separately, e.g. with app/console
`doctrine:phpcr:node:move /path/to/route/name /cms/routes/name`

the labels looking like this means that the translations are not found.
if you have your own admin, check the translation namespace you
specified. if its a default admin, you most likely need to clear the
cache to make symfony see the translation files.

**Comment by Yaghiyah** [comment]
Thanks for getting back to me. 

The admin tool labels are now displaying correctly, I did this. 

framework:
    translator:
        fallback: en

"there seems to be an issue with this when editing related routes on a
content that where placed at an invalid location previously"

Thanks is this logged as an issue ?

I will try this out then.
case you need to move the route separately, e.g. with app/console
`doctrine:phpcr:node:move /path/to/route/name /cms/routes/name
